import Providers from "@/components/Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";

import Head from "next/head";
import Login from "@/components/Login";
import SideBar from "@/components/SideBar";
import ToolkitProvider from "@/components/ToolkitProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log(session);
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>

      <body className={inter.className}>
        <Providers session={session}>
          {!session && <Login />}
          <ToolkitProvider>
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>
              <div className="bg-[#343541] flex-1">{children}</div>
            </div>
          </ToolkitProvider>
        </Providers>
      </body>
    </html>
  );
}
